#!/bin/bash
mkdir pgdata
mkdir uploads
# strips all chars except . from hostname
dots=${1//[^.]}
sed "s/REPLACE_WITH_HOSTNAME/${1}/; s/REPLACE_WITH_TLD_LENGTH/${#dots}/" scripts/defaultenv > env
echo DEVISE_SECRET=`openssl rand -base64 48` >> env
echo SECRET_COOKIE_TOKEN=`openssl rand -base64 48` >> env
echo PRIVATE_PUB_SECRET_TOKEN=`openssl rand -base64 48` >> env
