version: '2'
networks:
  default:

services:
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certificates:/etc/nginx/certs:rw
    volumes_from:
      - nginx

  nginx:
    image: jwilder/nginx-proxy
    networks:
      default:
        aliases:
          - REPLACE_WITH_HOSTNAME
          - faye.REPLACE_WITH_HOSTNAME
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certificates:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    links:
      - loomio
      - faye

  loomio:
    image: loomio/loomio
    networks:
      - default
    expose:
     - 3000
    env_file: ./env
    links:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/loomio_production
      # this is to tell nginx that you want requests for this hostname to come to the app
      - VIRTUAL_HOST=REPLACE_WITH_HOSTNAME
    volumes:
      - ./uploads:/loomio/public/system

  worker:
    image: loomio/loomio
    networks:
      - default
    env_file: ./env
    links:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    volumes:
      - ./uploads:/loomio/public/system
    command: "bundle exec rake jobs:work"

  db:
    image: postgres
    networks:
      - default
    volumes:
      - ./pgdata:/pgdata
    environment:
     - POSTGRES_PASSWORD=password
     - PGDATA=/pgdata

  mailin:
    image: loomio/mailin-docker
    networks:
      - default
    ports:
      - "25:25"
    links:
      - loomio
    environment:
      - WEBHOOK_URL=https://REPLACE_WITH_HOSTNAME/email_processor/

  faye:
    build: faye/.
    networks:
      - default
    env_file: ./faye_env
    environment:
      # this is to tell nginx that you want requests for this hostname to come to the app
      - VIRTUAL_HOST=faye.REPLACE_WITH_HOSTNAME
